[2021-03-20 07:41:29,783] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: spark-test.spark_job2 2021-03-20T07:41:26.773492+00:00 [queued]>
[2021-03-20 07:41:29,791] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: spark-test.spark_job2 2021-03-20T07:41:26.773492+00:00 [queued]>
[2021-03-20 07:41:29,791] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-20 07:41:29,791] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-03-20 07:41:29,791] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-20 07:41:29,801] {taskinstance.py:1063} INFO - Executing <Task(SparkSubmitOperator): spark_job2> on 2021-03-20T07:41:26.773492+00:00
[2021-03-20 07:41:29,803] {standard_task_runner.py:52} INFO - Started process 354 to run task
[2021-03-20 07:41:29,807] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'spark-test', 'spark_job2', '2021-03-20T07:41:26.773492+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/spark-test.py', '--cfg-path', '/tmp/tmpld67bsoi', '--error-file', '/tmp/tmpaojf066y']
[2021-03-20 07:41:29,808] {standard_task_runner.py:77} INFO - Job 5: Subtask spark_job2
[2021-03-20 07:41:29,833] {logging_mixin.py:104} INFO - Running <TaskInstance: spark-test.spark_job2 2021-03-20T07:41:26.773492+00:00 [running]> on host 088a9a82b7a0
[2021-03-20 07:41:29,857] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=admin@airflow.com
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=spark-test
AIRFLOW_CTX_TASK_ID=spark_job2
AIRFLOW_CTX_EXECUTION_DATE=2021-03-20T07:41:26.773492+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-03-20T07:41:26.773492+00:00
[2021-03-20 07:41:29,863] {base.py:74} INFO - Using connection to: id: spark_default. Host: spark://spark, Port: 7077, Schema: , Login: , Password: None, extra: XXXXXXXX
[2021-03-20 07:41:29,864] {spark_submit.py:363} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name Spark_Hello_World --class com.ibm.cdopoc.DataLoaderDB2COS --verbose --queue root.default --deploy-mode cluster /opt/airflow/hello-world.py /opt/airflow/airflow.cfg
[2021-03-20 07:41:29,917] {spark_submit.py:524} INFO - JAVA_HOME is not set
[2021-03-20 07:41:29,922] {taskinstance.py:1455} ERROR - Cannot execute: spark-submit --master spark://spark:7077 --name Spark_Hello_World --class com.ibm.cdopoc.DataLoaderDB2COS --verbose --queue root.default --deploy-mode cluster /opt/airflow/hello-world.py /opt/airflow/airflow.cfg. Error code is: 1.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1112, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1285, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1315, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 183, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 453, in submit
    self._mask_cmd(spark_submit_cmd), returncode
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name Spark_Hello_World --class com.ibm.cdopoc.DataLoaderDB2COS --verbose --queue root.default --deploy-mode cluster /opt/airflow/hello-world.py /opt/airflow/airflow.cfg. Error code is: 1.
[2021-03-20 07:41:29,923] {taskinstance.py:1503} INFO - Marking task as UP_FOR_RETRY. dag_id=spark-test, task_id=spark_job2, execution_date=20210320T074126, start_date=20210320T074129, end_date=20210320T074129
[2021-03-20 07:41:29,941] {local_task_job.py:146} INFO - Task exited with return code 1
